# should add loading of costum data, but editing a code file and a YAML file is almost the same difficulty 

COILED_COILS = dict(
    P5A = "ENAALEAKIAALKAKNAALKAEIAALEA",
    P7  = "EIQALEEKNAQLKQEIAALEEKNQALKY",
    N5  = "EIAALEAKIAALKAKNAALKAEIAALEA",
    N7  = "EIAALEAKNAALKAEIAALEAKIAALKA",
    N8  = "KIAALKAENAALEAKIAALKAEIAALEA",
)

LINKERS = "GSSGS SPGGS SGSSGS GGSGGG".split()